### ISSUE TITLE
best out of the box yet

### ISSUE THREAD

**Issue by silvacarl2** [mistralai/mistral-src#12]
I just tested this model on the hardest questions we use when evaluating models.  It got 85% right, beating larger models at these questions.   This is the first time I have ever seen this.

And we have tested everything.

If it can be easily fine tuned, this would be perfect.

**Comment by Bam4d** [comment]
We have a discord channel dedicated to fine-tuning! https://discord.com/channels/1144547040454508606/1156994197287612508
