### ISSUE TITLE
M1 Support?

### ISSUE THREAD

**Issue by ControlCplusControlV** [mistralai/mistral-src#2]
I was testing the `one_file_rey.py` on my m1 pro 32 gb unified memory, and was running into issues relating to converting the model to use `mps` or even `cpu` instead, ran into this first

```
NotImplementedError: The operator 'aten::view_as_complex' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

So with that flag enabled I run into

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
```

so switching everything to cpu even though it will be slow af results in 

```
RuntimeError: "log_vml_cpu" not implemented for 'Half'
```

Any ideas, or do I simply have to learn how to configure a CUDA runtime properly?

**Comment by olso** [comment]
Maybe this is a different approach https://advanced-stack.com/resources/running-inference-using-mistral-ai-first-released-model-with-llama-cpp.html ?

**Comment by olso** [comment]
Another approach https://ollama.ai

**Comment by ControlCplusControlV** [comment]
Thank you, testing out `ollama` now if not I will try ggml and pr a demo script using that

**Comment by ControlCplusControlV** [comment]
Ollama support worked, thank you @olso
