### ISSUE TITLE
System prompt handling in chat templates for Mistral-7b-instruct

### ISSUE THREAD

**Issue by jamesr66a** [mistralai/mistral-src#35]
Hello, we are trying to implement chat completion over Mistral-7b-instruct and we are trying to figure out how to handle system prompts. Different information sources either omit this or are conflicting:

* The [docs](https://docs.mistral.ai/llm/mistral-instruct-v0.1#chat-template) and [HF model card](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1) states the following, but does not go into any detail about how to handle system prompts:

In order to leverage instruction fine-tuning, your prompt should be surrounded by [INST] and [\INST] tokens. The very first instruction should begin with a begin of sentence id. The next instructions should not. The assistant generation will be ended by the end-of-sentence token id.

E.g.

text = "< s >[INST] What is your favourite condiment? [/INST]"
"Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen!</ s > "
"[INST] Do you have mayonnaise recipes? [/INST]"

* HuggingFace's `apply_chat_template` uses `<<SYS>>`/`<</SYS>>` tokens to delineate the system prompt embedded within the first instruction:
```
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained("/root/Mistral-7b-instruct-hf")
tokenizer = AutoTokenizer.from_pretrained("/root/Mistral-7b-instruct-hf")

messages = [
    {"role": "system", "content": "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature."},
    {"role": "user", "content": "Write me a recipe for tacos al pastor"},
]

encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

model_inputs = encodeds.to(device)
model.to(device)

generated_ids = model.generate(model_inputs, max_new_tokens=1000, do_sample=True)
decoded = tokenizer.batch_decode(generated_ids)
print(decoded[0])
"""
<s> [INST] <<SYS>>
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.
<</SYS>>

Write me a recipe for tacos al pastor [/INST] Tacos al Pastor Recipe
"""
```

* FastChat does not seem to support system prompts https://github.com/lm-sys/FastChat/pull/2483/files

What is the definitive answer for how to handle system prompts with Mistral-7b-instruct?

**Comment by TikaToka** [comment]
have you solved this one?

**Comment by jamesr66a** [comment]
The mistral team has published this information on the docs: https://docs.mistral.ai/usage/guardrailing/#appendix

Closing now

**Comment by Cyb3rWard0g** [comment]
Hey @jamesr66a ! But how does that work? Were you able to update the default system prompt?

**Comment by druskacik** [comment]
>  https://docs.mistral.ai/usage/guardrailing/#appendix

The link is no longer active.

**Comment by jadedgnome** [comment]
> > https://docs.mistral.ai/usage/guardrailing/#appendix
> 
> The link is no longer active.

https://web.archive.org/web/20231030013339/https://docs.mistral.ai/usage/guardrailing/#appendix

https://docs.mistral.ai/platform/guardrailing
