### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [mistralai/mistral-src#37]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/Mistral-colab

**Comment by mahimairaja** [comment]
Great one @camenduru 

Do you know? What would be the ideal embedding sentence transformer for Mistral 7B Instruct? 

Will [bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5?text=Hello) Works with it?
