### ISSUE TITLE
No safetensors in HF model card?

### ISSUE THREAD

**Issue by EricLBuehler** [mistralai/mistral-src#74]
Hello everybody,

I have noticed that there are only `.bin` files and no `.safetensors` files in the model card (https://huggingface.co/mistralai/Mistral-7B-v0.1/tree/main). Could this be officially added? There appear to be some other models on HF Hub that have safetensors or other formats: https://huggingface.co/alpindale/mistral-7b-safetensors, but I was wondering if an official `.safetensors` release could be added?

**Comment by Abhinay1997** [comment]
Seems to have been added a few days ago. Can see the files in the official repo.

**Comment by EricLBuehler** [comment]
Great!
